name: Demo

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo 'Running fake tests...'
          echo 'All fake tests passed!'

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.1

      - name: Run a one-line script
        run: ls -l

      - name: Build node project
        run: |
          npm install
          npm run build
        
  deploy:
    runs-on: ubuntu-latest
    needs: [checkout, build]
    steps:
      - name: Publish to surge.sh
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          domain: 'wh-hello-world.surge.sh'
          project: './build'
          login: willhtun42@gmail.com
          token: 18e351239d2d78b16a791dd293626132